# Generated by Django 4.1.5 on 2023-01-27 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile", old_name="imgage", new_name="image",
        ),
    ]
